# Generated by Django 5.0.7 on 2024-07-31 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetails',
            name='number',
        ),
        migrations.AddField(
            model_name='persondetails',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.team'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
