# Generated by Django 5.0.7 on 2024-08-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_persondetails_number_persondetails_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('palce', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
